### ISSUE TITLE
مشکل در تعویض ماه

### ISSUE THREAD

**Issue by apapar** [Rmanaf/jalali-datepicker#1]
باعرض سلام و خسته نباشید خدمت توسعه دهنده محترم
زمانی که تاریخ آخر ماه باشه و دکمه ماه قبل یا ماه بعد رو میزنی
یا از تو منو ماه قبلی یا ماه بعدی رو انتخاب میکنی
جدول یه ماه بیشتر اسکیپ میکنه

مثلا شما دستی 30 دی رو انتخاب کنید
سپس دکمه ماه بعدی رو بزنید
جای اینکه بره تو بهمن، میره تو اسفند
از منو بالا هم بهمن رو انتخاب کنید، اسفند باز میشه

**Comment by Rmanaf** [comment]
Thanks for bringing this to my attention. I've fixed the problem in the library by replacing 'month' with 'jMonth'. Now it's working as expected. If you have any more questions or run into issues, feel free to let me know.

```js
 _o.date = _o.date.clone().add(1, 'jMonth');
 ```

**Comment by Rmanaf** [comment]
Since I didn't get any feedback from you, I'm closing this issue. If you encounter any other problems, please open a new one.

**Comment by apapar** [comment]
> Thanks for bringing this to my attention. I've fixed the problem in the library by replacing 'month' with 'jMonth'. Now it's working as expected. If you have any more questions or run into issues, feel free to let me know.
> 
> ```js
>  _o.date = _o.date.clone().add(1, 'jMonth');
> ```

Hello again
the problem still exists in the select menu
i changed this code
`i.date=o>0?i.date.clone().add(o,"month")`
with this code
`i.date=o>0?i.date.clone().add(o,"jMonth")`
and it's done
thank you
